name: Deploy to Databricks Dev

on:
  push:
    branches:
      - dev_collaboration
    paths-ignore:
      - .github/**
      - bundle_config/**

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev    
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEPLOYMENT_TARGET_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@amin

      # - name: Validate Databricks bundle
      #   run: databricks bundle validate --target dev

      - name: Deploy bundle to Dev
        run: databricks bundle deploy --target dev
